version: '3.9'

services:
  client:
    container_name: client-container
    environment:
      REACT_APP_API_URL: http://localhost:8080
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "./client/node_modules:/src/node_modules"
    stdin_open: true
  server:
    container_name: server-container
    environment:
      DB_CONNECT: mongodb://mongo:27017/HappyNotes
      TOKEN_SECRET: afbneofjbnouefnvijsdfnbvweruin
      PORT: 8080
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/src
      - ./server/node_modules:/src/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"